@url_dev = http://localhost:3052/v1/api

### signUp
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 2a02e59c6d395e945d811e3bf6706c5588ebafda26eecc3a33ef772b57194c7add50f715367ddf9b726c56565b5e0f3b008f85e5201d45f7c45b300330ea153a

{
    "name": "ShopTest01",
    "email": "test11@gmail.com",
    "password": "abc123"
}


### login
POST {{url_dev}}/shop/login
Content-Type: application/json

{
    "email": "test11@gmail.com",
    "password": "abc123"
}