@url_dev = http://localhost:3052/v1/api

### signUp
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 9bcfedd01ca23bd4fa2e5ea3a1a219b759200066093e300ea62ec5bbf106f748ccc58a89aa44644a78740024d0d428cad54bc5126582cab6f86986244285bb45

{
    "name": "ShopTest02",
    "email": "test02@gmail.com",
    "password": "abc123"
}


### login
POST {{url_dev}}/shop/login
Content-Type: application/json

{
    "email": "test11@gmail.com",
    "password": "abc123"
}